---
config:
  theme: default
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	assistant_node(assistant_node)
	collect_info_node(collect_info_node)
	response_builder_node(response_builder_node)
	__end__([<p>__end__</p>]):::last
	__start__ --> assistant_node;
	assistant_node --> collect_info_node;
	collect_info_node -. &nbsp;not fulfill&nbsp; .-> assistant_node;
	collect_info_node -. &nbsp;info all collected&nbsp; .-> response_builder_node;
	response_builder_node --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
