---
config:
  theme: default
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	Node1(Node1)
	Node2(Node2)
	__end__([<p>__end__</p>]):::last
	Node1 --> Node2;
	Node2 -. &nbsp;True&nbsp; .-> Node1;
	Node2 -. &nbsp;False&nbsp; .-> __end__;
	__start__ --> Node1;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
